### ISSUE TITLE
Making the driver work with dbeaver

### ISSUE THREAD

**Issue by AmmarSalmi** [leonhad/paradoxdriver#40]
Is it possible to allow this driver to work with dbeaver. If it's already possible. Can you please write a tutorial?

**Comment by leonhad** [comment]
Hi Ammar Salmi, I have plans to do it very soon, so I take some pictures, maybe it helps. This version the tables names don’t show up, but it works. The next version this will be fixed. Regards,Leonardo Costa De: AmmarSalmiEnviado:quinta-feira, 25 de novembro de 2021 08:29Para: leonhad/paradoxdriverCc:SubscribedAssunto: [leonhad/paradoxdriver] Making the driver work with dbeaver (Issue #40) Is it possible to allow this driver to work with dbeaver. If it's already possible. Can you please write a tutorial?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leonhad** [comment]
https://github.com/leonhad/paradoxdriver/wiki/DBeaver

**Comment by AmmarSalmi** [comment]
Thank you for the quick response. You deserve all the stars in the world, not just 5.

**Comment by leonhad** [comment]
Thank you

**Comment by AmmarSalmi** [comment]
The connection is enlisting all the directories in my hardrive not just the directory I mentioned to be the path for my database. I tried changing the URL to {folder} instead of {database} and it's the same problem. 
![image](https://user-images.githubusercontent.com/7024839/143455878-f62e0842-5bdd-42f1-b66f-4f0751824311.png)
Even if I open the database directory the tables still don't show up. I followed the tutorial in the wiki to the letter. Sorry to trouble you.

**Comment by leonhad** [comment]
The current version has a bug in table listing. I fixed this in version 6.0, but I don´t publish it yet. The SELECT statements still works even the tables don´t.

**Comment by AmmarSalmi** [comment]
I will be waiting for the release. Thanks.

**Comment by leonhad** [comment]
Hi,

I publish the version 1.6.0 in GitHub and Maven Central. The GitHub is up now, but the Maven Central takes time (about 24h). You can test it when it is up.
